Portfolio Desktop Version
rahimialijan/Portfolio-Mobile-Contact-Form- pull request #5
Opened 2023-04-03 06:23 UTC by rahimialijan

# Portfolio Desktop Version Project:
1-Add media query for the desktop version
2-Use a grid layout system for  outer containers
3-Fix all linter errors

2023-04-05 13:55 UTC, IngDavidTM requested changes
## Hi @rahimialijan 🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [ ] I noticed that some of the colors on your page, such as the titles and paragraphs, do not match the required colors in the Figma template. For example, the main title should have a color code of #172B4D instead of #000000. I kindly request that you make the necessary adjustments to ensure that all colors on your page match the design in the Figma template accurately. Doing so will improve the overall consistency and coherence of your design :+1:.

**Your design**

![Screenshot from 2023-04-05 08-54-56](https://user-images.githubusercontent.com/105117832/230102675-34e7d95d-35d1-45b2-ba25-092bfac3c3d1.png)

**Figma**

![Screenshot from 2023-04-05 08-55-09](https://user-images.githubusercontent.com/105117832/230102742-23336d89-329f-48e1-8839-d4eaf1930ba6.png)


- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 13:55 UTC, IngDavidTM commented on style.css
> +  }
- [ ] Your project styling is fantastic, but I would like to make a suggestion to further improve it. Specifically, I recommend adjusting the positioning of the button with the arrow, moving it up to match the design in the Figma template more closely. Making this change will help ensure consistency in the design and improve the overall appearance of the project.

**Your design**

![Screenshot from 2023-04-05 08-44-59](https://user-images.githubusercontent.com/105117832/230100265-58ff0232-3b15-451d-acd5-ba3f39286e40.png)

**Figma**

![Screenshot from 2023-04-05 08-44-46](https://user-images.githubusercontent.com/105117832/230100344-f1794ee9-1a4f-4651-93d4-a4b1f67b8fff.png)

2023-04-05 15:58 UTC, rahimialijan commented on style.css
> +  }
Dear @IngDavidTM ,
I made the required changes please check, thanks for your guidance

2023-04-05 16:19 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/YPI7uEvEZr7siYRlZD/giphy.gif)

# Hi @rahimialijan 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- UI is looking on point ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 16:19 UTC, AbelG101 commented on style.css
_**THE BELOW COMMENT IS MARKED [OPTIONAL] BECAUSE THE PREVIOUS REVIEWER FORGOT TO MENTION IT BUT I HIGHLY ADVISE YOU TO CHECK IT OUT AS IT'S A PROJECT REQUIREMENT**_
https://github.com/rahimialijan/Portfolio-Mobile-Contact-Form-/blob/fa7a86ba44f6a4091969bacf39c66a2f89a14561/style.css#L461-L465
- [ ] [OPTIONAL] I'd like to apologize as the previous reviewer forgot to mention this but please make sure you stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-468&t=PBimssV7iaLZjIVt-0) as this ensures your future clients that you can implement a given design down to the last pixel 🔎.  The above `:hover` state styling you added looks neat but let's make sure we follow the design next time 👨‍🎤.
- Here's the Figma design for the buttons as a reminder: 😉
      ![firefox_kz6PEcoelc](https://user-images.githubusercontent.com/104968236/230141740-0d2bfd95-0d41-490b-b074-b297ebb42daf.png)

2023-04-05 16:48 UTC, merged

2023-04-06 07:11 UTC, AbelG101 commented on style.css
Great work @rahimialijan 👏.